### ISSUE TITLE
How to correcttly run the program?

### ISSUE THREAD

**Issue by blackcoding** [filu005/SPH#1]
Could you offer me a document which guide me to run the program and tell me what environment need to be ready.

**Comment by filu005** [comment]
In short:
Dependencies: [GLM](http://glm.g-truc.net/0.9.8/index.html), [GLEW](http://glew.sourceforge.net/), [GLFW](http://www.glfw.org/), [SOIL](http://www.lonesock.net/soil.html).
I compile the project with Visual Studio 2013; proper project file is in this repository (z-index sort.vcxproj). I've never tried to run it on linux or compile it with GCC (but I suspect that there wouldn't be any major problem for it to work).

Filip

**Comment by blackcoding** [comment]
![image](https://cloud.githubusercontent.com/assets/16200805/20783733/bab34126-b7d0-11e6-8952-8cac9badbeaf.png)
It's the Screenshots which I get from the program. I'm not sure that it's right. I doubt that SOIL .lib is not right! Can you show your result form the program by Screenshots

**Comment by filu005** [comment]
That's basicly right; shading is a bit off, maybe I'll fix it some day.
It should look like this: [video](https://youtu.be/xNh_8Bn85KQ)

**Comment by blackcoding** [comment]
![image](https://cloud.githubusercontent.com/assets/16200805/20966509/9ad2f38a-bcb5-11e6-8852-7d21026350c6.png)
I correctly run the program. But on my PC, the program run so slow, we can get it from Screenshots. I found that my program's fps is smaller tenfold than yours which I can see from the video? How to solve the it? I don't modify any parameter.
![Uploading image.png…]
Why the fluid splash like the Screenshot?
And if I want to replace the background picture, what should I  pay attention to?
Poor English.
Thank you very much!

**Comment by filu005** [comment]
Did you turn on the compiler optimizations (Release build in visual studio)?
There are several bottlenecks in the program: overall physical simulation (heavy influenced by number of particles), pre-render part - generating 'distance field' (see DistanceFiled::generate_field_from_surface_particles method) and raycasting (take a look at distance_field_raymarching.frag shader). You can fiddle around with these parts of code, change corresponding parameters and see if your frame rate improves.

As a background I use cube map (textures/skybox). But beware, I use it also for fluid surface color/reflection (see 'skybox' in distance_field_raymarching.frag shader).
